### PR TITLE
add posters D-06 and D-08

### PR DESCRIPTION
**Pull request by adrienycart**

### CODE REVIEW

**Comment by keunwoochoi** [comment]
Hi, thanks! One thing - could you rename the poster files to be more similar to others (and readme.md accordingly)?

**Comment by adrienycart** [comment]
Sure, sorry about that, I'll do that later tonight/tomorrow!


Le lun. 9 déc. 2019 à 16:38, Keunwoo Choi <notifications@github.com> a
écrit :

**Comment by adrienycart** [comment]
I renamed the files, let me know if there is anything I can do!

**Comment by keunwoochoi** [comment]
Thanks! One thing - the new filenames are not updated on the readme.md yet. I could fix it too but I guess it'd be better to have a correct readme on your repo :-)

**Comment by adrienycart** [comment]
Of course I forgot to do that...
It's done now!
Thanks a lot!

**Comment by keunwoochoi** [comment]
Fortunately there have been many similar training samples haha. Thanks!

**Pull request merged**
