### PR TITLE
E-05: The Harmonix Set

### PR DESCRIPTION
**Pull request by urinieto**
Adding the poster for paper E-05. Also, I think having all the PNGs loaded in the README is not a great idea, so I simply added a link to mine.

### CODE REVIEW

**Comment by keunwoochoi** [comment]
Hey, thanks! I agree that loading a lot of png files is not so great. But being able to see posters without any active effort is the point in my opinion. How about I separate them by maybe session once we have enough posters, say, more than 20?

**Comment by urinieto** [comment]
Sounds good, even though the other issue is that I uploaded a PDF and I'm not sure if MD can render them as images... do you want me to put a PNG instead?

**Comment by keunwoochoi** [comment]
Yup, png sounds good.

**Comment by keunwoochoi** [comment]
Hey, I just did it by myself. Thanks for the poster! (and the dataset!)

**Comment by urinieto** [comment]
Oh thanks! Totally forgot about this :_D

**Pull request closed without merging**
