### PR TITLE
Add [A-09] poster

### PR DESCRIPTION
**Pull request by LPorcaro**

### CODE REVIEW

**Comment by keunwoochoi** [comment]
Hi, thanks! Would you mind to attach an image file and embed it in the markdown instead of a link to pdf?

**Comment by LPorcaro** [comment]
No problem

**Comment by keunwoochoi** [comment]
thanks! the format to embed an image is to put ! at the beginning of the line, but i'll do it.

**Comment by LPorcaro** [comment]
thanks!

**Pull request merged**
